server:
  port: 8090
##elasticsearch:
  ##url: http://localhost:9200/
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  jackson:
    serialization:
      write_dates_as_timestamps: false
